#!/bin/sh

## Get OSD-Information
if [ -f /opt/media/sdc/config/osd.conf ]; then
    source /opt/media/sdc/config/osd.conf  2>/dev/null
    # Call setconf only if we have something to set, to avoid outputing error messages
    [ ! -z "${OSD}" ] && /opt/media/sdc/bin/setconf -k o -v "${OSD}" 2>/dev/null
    [ ! -z "${COLOR}" ] && /opt/media/sdc/bin/setconf -k c -v ${COLOR} 2>/dev/null
    [ ! -z "${SIZE}" ] && /opt/media/sdc/bin/setconf -k s -v ${SIZE} 2>/dev/null
    [ ! -z "${POSY}" ] && /opt/media/sdc/bin/setconf -k x -v ${POSY} 2>/dev/null
    [ ! -z "${FIXEDW}" ] && /opt/media/sdc/bin/setconf -k w -v ${FIXEDW} 2>/dev/null
    [ ! -z "${SPACE}" ] && /opt/media/sdc/bin/setconf -k p -v ${SPACE} 2>/dev/null
    [ ! -z "${FONTNAME}" ] && /opt/media/sdc/bin/setconf -k e -v ${FONTNAME} 2>/dev/null

else
    /opt/media/sdc/bin/setconf -k o -v ""
fi
