#!/bin/sh
SERVICE_NAME="IR Led"
export LD_LIBRARY_PATH='/opt/media/sdc/lib/:/lib/:/ipc/lib/'

. /opt/media/sdc/scripts/common_functions.sh

status()
{
  state=$(ir_led status)
  if [[ $state == "ON" || $state == "on" ]]; then
    echo "PID: OK" 
  fi
}

start()
{
  ir_led on
}

stop()
{
  ir_led off
}

if [ $# -eq 0 ]; then
  start
else
  case $1 in start|stop|status)
    $1
    ;;
  esac
fi

