#!/bin/sh
SERVICE_NAME="Network Monitor"
PIDFILE="/var/run/network-monitor.pid"

if [ ! -f /opt/media/sdc/config/netmon.conf ]; then
  echo "You have to configure network monitor first. Please see /opt/media/sdc/config/netmon.conf for further instructions"
fi

status()
{
  pid="$(cat "$PIDFILE" 2>/dev/null)"
  if [ "$pid" ]; then
    kill -0 "$pid" >/dev/null && echo "PID: $pid" || return 1
  fi
}

start()
{
  if [ -f $PIDFILE ]; then
    echo "Network Monitor already running";
  else
    echo "Starting Network Monitor"
    /opt/media/sdc/bin/busybox nohup /opt/media/sdc/scripts/network-monitor.sh &>/dev/null &
    echo "$!" > "$PIDFILE"
  fi
}

stop()
{
  pid="$(cat "$PIDFILE" 2>/dev/null)"
  if [ "$pid" ]; then
     kill "$pid" && rm "$PIDFILE"
  fi
}

if [ $# -eq 0 ]; then
  start
else
  case $1 in start|stop|status)
    $1
    ;;
  esac
fi
