#!/bin/sh
SERVICE_NAME="ONVIF Discovery"
PIDFILE="/var/run/onvif.pid"
WATCHDOG_PIDFILE="/var/run/onvif-watch.pid"
export LD_LIBRARY_PATH='/opt/media/sdc/lib/:/thirdlib:/system/lib/:/ipc/lib/'

. /opt/media/sdc/scripts/common_functions.sh

if [ ! -f /opt/media/sdc/config/onvif.conf ]; then
  cp /opt/media/sdc/config/onvif.conf.dist /opt/media/sdc/config/onvif.conf
fi

if [ -f /opt/media/sdc/config/onvif.conf ]; then
  . /opt/media/sdc/config/onvif.conf
fi

if [ ! -f /opt/media/sdc/config/rtspserver.conf ]; then
  cp /opt/media/sdc/config/rtspserver.conf.dist /opt/media/sdc/config/rtspserver.conf
fi

if [ -f /opt/media/sdc/config/rtspserver.conf ]; then
  . /opt/media/sdc/config/rtspserver.conf
fi

status()
{
  pid="$(cat "$PIDFILE" 2>/dev/null)"
  if [ "$pid" ]; then
    # Prints PID: $pid if exists and returns 0(no error) else returns 1(error condition)
    kill -0 "$pid" >/dev/null && echo "PID: $pid" || return 1
  fi
}

start()
{
  if [ "$(status)" != "" ]; then
    echo "A ONVIF Discovery service is already running, please stop it or reboot"
  else
    echo "Starting ONVIF Discovery service"
    
    LOGPATH="/dev/null"

    /opt/media/sdc/bin/monvifd -p $ONVIF_PORT -w 443 -wp https -r $PORT -en2 0 -hwn $HW_NAME -vnn $VENDOR_NAME -dn $DEVICE_NAME -mod $DEVICE_MODEL \
        -rp1 unicast -vwh1 "${RTSPH264OPTS}" -vc1 H264 -vcb1 $BITRATE -fps1 $FRAMERATE_NUM 2>> "$LOGPATH" >> "$LOGPATH" &
    echo "$!" > "$PIDFILE"

    ## Watchdog
    if ! checkpid "$WATCHDOG_PIDFILE"; then
      /opt/media/sdc/scripts/service-watchdog.sh /opt/media/sdc/controlscripts/onvif 0 &
      echo "$!" > "$WATCHDOG_PIDFILE"
    fi
  fi
}

stop()
{
  killpid "$WATCHDOG_PIDFILE"
  killpid "$PIDFILE"
}

if [ $# -eq 0 ]; then
  start
else
  case $1 in start|stop|status)
    $1
    ;;
  esac
fi
